version: '3'
services:
  postgre_db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: test
  test_app:
    image: 'test_app.jar'
    ports:
      - "8080:8080"
    depends_on:
      - postgre_db